---
name: CI

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read

jobs:
  build-linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: 1.18.4

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make all examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make all examples test

  build-macos-amd64:
    runs-on: macos-latest
    steps:
    - name: Set up go
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
      with:
        go-version: 1.18.4

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        path: ${{ env.GOPATH }}/src/k8s.io/kops

    - name: make kops examples test
      working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
      run: |
        make kops examples test

  build-windows-amd64:
    runs-on: windows-2019
    steps:
    - name: Set up go
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
      with:
        go-version: 1.18.4

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        path: ${{ env.GOPATH }}/src/k8s.io/kops

    - name: make kops examples test
      working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
      run: |
        make kops examples test-windows

  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: 1.18.4

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make quick-ci
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make quick-ci
